// Generated by NovaComp --emit-cuda
#include <stdio.h>
#include <stdlib.h>
#include <cuda_runtime.h>
#include <math.h>

#define CUDA_CHECK(call) \
    do { \
        cudaError_t err = call; \
        if (err != cudaSuccess) { \
            fprintf(stderr, "CUDA error at %s:%d: %s\n", \
                    __FILE__, __LINE__, cudaGetErrorString(err)); \
            exit(1); \
        } \
    } while(0)

__global__ void matmul_kernel(float* A, float* B, float* C, int M, int K, int N) {
    int row = blockIdx.y * blockDim.y + threadIdx.y;
    int col = blockIdx.x * blockDim.x + threadIdx.x;
    if (row < M && col < N) {
        float sum = 0.0f;
        for (int k = 0; k < K; k++)
            sum += A[row * K + k] * B[k * N + col];
        C[row * N + col] = sum;
    }
}

__global__ void relu_kernel(float* A, float* C, int n) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n) C[i] = A[i] > 0.0f ? A[i] : 0.0f;
}

int main() {
    srand(42);

    /* tensor d_t0 (32x32) */
    float *h_t0 = (float*)malloc(1024 * sizeof(float));
    float *d_t0;
    CUDA_CHECK(cudaMalloc(&d_t0, 1024 * sizeof(float)));
    for (int i = 0; i < 1024; i++) h_t0[i] = (float)rand() / RAND_MAX;
    CUDA_CHECK(cudaMemcpy(d_t0, h_t0, 1024 * sizeof(float), cudaMemcpyHostToDevice));

    /* tensor d_t1 (32x32) */
    float *h_t1 = (float*)malloc(1024 * sizeof(float));
    float *d_t1;
    CUDA_CHECK(cudaMalloc(&d_t1, 1024 * sizeof(float)));
    for (int i = 0; i < 1024; i++) h_t1[i] = (float)rand() / RAND_MAX;
    CUDA_CHECK(cudaMemcpy(d_t1, h_t1, 1024 * sizeof(float), cudaMemcpyHostToDevice));

    /* matmul: d_t2 = d_t0 x d_t1 (32x32) */
    float *h_t2 = (float*)malloc(1024 * sizeof(float));
    float *d_t2;
    CUDA_CHECK(cudaMalloc(&d_t2, 1024 * sizeof(float)));
    {
        dim3 block(16, 16);
        dim3 grid((32 + 15) / 16, (32 + 15) / 16);
        matmul_kernel<<<grid, block>>>(d_t0, d_t1, d_t2, 32, 32, 32);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    }

    /* relu: d_t3 = relu(d_t2) */
    float *h_t3 = (float*)malloc(1024 * sizeof(float));
    float *d_t3;
    CUDA_CHECK(cudaMalloc(&d_t3, 1024 * sizeof(float)));
    {
        int threads = 256;
        int blocks = (1024 + threads - 1) / threads;
        relu_kernel<<<blocks, threads>>>(d_t2, d_t3, 1024);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    }

    /* copy result back */
    CUDA_CHECK(cudaMemcpy(h_t3, d_t3, 1024 * sizeof(float), cudaMemcpyDeviceToHost));
    printf("Result[0..4]: ");
    for (int i = 0; i < 5 && i < 1024; i++) printf("%.4f ", h_t3[i]);
    printf("\n");

    cudaFree(d_t0);
    free(h_t0);
    cudaFree(d_t1);
    free(h_t1);
    cudaFree(d_t2);
    free(h_t2);
    cudaFree(d_t3);
    free(h_t3);

    return 0;
}
